<a href="https://colab.research.google.com/github/Sonu-kumar-08/YBI-INTERNSHIP/blob/main/oops_and_data_analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
#encapsulation
#private cannot be accessed outside of class
#why do we need Encapsulation?
'''Protects data from unauthorized acess and accidental modification
  contols data updates using getter/setter method with validation
  enhances modulation by hiding internal implementation details
  Simplifies maintainance through centralized data handling logic
  '''
class Employee:
    def __init__(self, name, salary):
        self.name = name
        self.__salary = salary

    def get_salary(self):
        return self.__salary

emp = Employee("Fedrick", 5000)

print(emp.name)
print(emp.get_salary())

Fedrick
5000

In [110]:
class BankAccount:
    def __init__(self,balance):
      self._balance = balance

    def deposit(self,amount):
      self._balance += amount

    def withdraw(self,amount):
        if amount > 0 and amount <= self._balance:
            self._balance -= amount
        else:
          print("invalid withdrawl")
    def display_balance(self):
        print(f"balance: {self._balance}")
emp= BankAccount(50000)
emp.deposit(10000)
emp.withdraw(20000)
emp.display_balance()

balance: 40000

In [111]:
class Student:
  def __init__(self, Name ,Marks):
    self.Name = Name
    self.Marks = Marks

  def display(self):
    print(f"Name: {self.Name}")
    print(f"Marks: {self.Marks}")

  def Updatename(self, upName):
    self.Name=upName
    print(f"Updated Name: {self.Name}")

s= Student("Sonu",90)
s.Updatename("priyam")
s.display()

Updated Name: priyam
Name: priyam
Marks: 90

In [112]:
class Student:
    def __init__(self, Name, Marks, regno):
        self.Name = Name
        self.Marks = Marks
        self._regno = regno

    def display(self):
        print(f"Name: {self.Name}")
        print(f"Marks: {self.Marks}")
        print(f"Regno: {self._regno}")

    def Updatemark(self, Upmark):
        self.PreviousMarks = self.Marks
        self.Marks = Upmark

        print(f"Previous marks: {self.PreviousMarks}")
        print(f"Updated marks: {self.Marks}")


s = Student("Sonu", 89, 101)

s.Updatemark(90)
s.display()

Previous marks: 89
Updated marks: 90
Name: Sonu
Marks: 90
Regno: 101

In [113]:
#ABSTRACTION
from abc import ABC, abstractmethod
class BankApp(ABC):
    def database(self):
      print("connected to database")

    @abstractmethod
    def security(self):
      pass
class MobileApp(BankApp):
  def mobile_login(self):
    print("login to mobile")

  def security(self):
    print("mobile security")

In [114]:
mob = MobileApp()

In [115]:
mob.database()
mob.mobile_login()

connected to database
login to mobile

In [116]:
mob.security()

mobile security

In [117]:
from abc import ABC, abstractmethod

class Vehicle(ABC):
  @abstractmethod
  def start(self):
    pass

  def start (self):
    print("connected to database")

In [118]:
#.polymorphism
#.Write reusable code
#.Reduce code complexity
#.make program flexible
#.easy add new classes
#.improve maintainability
#.use a common interface for different object
class Bird:
  def move(self):
    print("Bird moves by flying")

class Fish:
  def move(self):
    print("fish moves by swim")

class Car:
  def move(self):
    print("car moves by start")

object = [Bird(),Fish(),Car()]
for obj in object:
  obj.move()

Bird moves by flying
fish moves by swim
car moves by start

In [119]:
print(len("python"))
print(len([10,20,30,40,50]))
print(len((1,2,3,4,5)))

6
5
5

In [120]:
class calculator:
  def add(self,a,b):
    return a+b
  def add(self,a,b,c):
    return a+b+c
cal = calculator()
print(cal.add(10, 20, 30))

60

In [121]:
#(*)as much as parameter we can take by using * function
class calculator:
  def add (self,*number):
    return sum(number)

obj = calculator()
print(obj.add(10,20,30,))
print(obj.add(10,20,30,40,))
print(obj.add(10,20,30,40,50))

60
100
150

In [122]:
class Student:
  def info (self, *Name):
    print(*Name)

obj = Student()
obj.info("sonu")
obj.info(20)
obj.info("BCA")

sonu
20
BCA

In [123]:
#method overrding
class Animal:
  def sound(self):
    print("Animal makes a sound")

class Dog(Animal):
  def sound(self):
    print("Dog barks")

class Cat(Animal):
  def sound(self):
    print("Cat meows")


dog = Dog()
cat = Cat()

dog.sound()
cat.sound()

Dog barks
Cat meows

In [124]:
#runtime Polymorphism using inheritance
class Vehical:

    def start(self):
        print("Vehicle starts")


class Car(Vehical):

    def start(self):
        print("Car starts with start button")


class Bike(Vehical):

    def start(self):
        print("Bike starts with start button")


vehi = Car()
vehi.start()

vehi = Bike()
vehi.start()

Car starts with start button
Bike starts with start button

In [125]:
class Cat:
  def sound(self):
    print("meow")

class Cow:
  def sound(self):
    print("Moo")

class Dod:
  def sound(self):
    print("Barks")

obj=[ Cat(), Cow(), Dod()]
for obj in obj:
  obj.sound()

meow
Moo
Barks

In [126]:
class Car:
    def move(self):
        print("Car moves on the road")


class Bird:
    def move(self):
        print("Bird flies in the sky")


def start_movement(obj):
    obj.move()


start_movement(Car())
start_movement(Bird())

Car moves on the road
Bird flies in the sky

In [127]:
def display(*data):
  for value in data:
    print(value)
display(100)
display("python")
display(1,2,3)
display("Name : Sonu")

100
python
1
2
3
Name : Sonu

In [128]:
#data analtics
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
print("Array:\n", arr)
print("Shape", arr.shape)
print("Dimesions", arr.ndim)

Array:
 [[1 2 3]
 [4 5 6]]
Shape (2, 3)
Dimesions 2

In [129]:
import numpy as np

a=np.array([10,20,30])
b=np.array([1,2,3])

print("Addition", a+b)
print("Subtraxtion", a-b)
print("Multiplication", a*b)
print("Divsion", a/b)

Addition [11 22 33]
Subtraxtion [ 9 18 27]
Multiplication [10 40 90]
Divsion [10. 10. 10.]

In [130]:
arr=np.array([10,20,30,40])

print("First element: ", arr[0])
print("last element: ", arr[-1])
print("slicing element: ", arr[1:3])

First element:  10
last element:  40
slicing element:  [20 30]

In [131]:
import pandas as sm

data=[10,20,30,40]
series=sm.Series(data)

print(series)
print("First element: ", series[0])
print("slicing element: ", series[1:3])

0    10
1    20
2    30
3    40
dtype: int64
First element:  10
slicing element:  1    20
2    30
dtype: int64

In [132]:
data ={
    "Name": ["A","B","C"],
    "Age": [20,30,40]
}

df=sm.DataFrame(data)
print(df)
print("Column Access:\n", df["Name"])
print("Row Access:\n", df.loc[1])
print(sm)

  Name  Age
0    A   20
1    B   30
2    C   40
Column Access:
 0    A
1    B
2    C
Name: Name, dtype: object
Row Access:
 Name     B
Age     30
Name: 1, dtype: object
<module 'pandas' from '/usr/local/lib/python3.13/dist-packages/pandas/__init__.py'>

In [133]:
df=sm.read_csv("/content/bollywood.csv")

In [134]:
df.head()

,SlNo,ReleaseDate,MovieName,ReleaseTime,Genre,Budget,BoxOfficeCollection,YoutubeViews,YoutubeLikes,YoutubeDislikes
0,1,18-Apr-14,2States,LW,Romance,36,104.00,8576361,26622,2527
1,2,4-Jan-13,TableNo.21,N,Thriller,10,12.00,1087320,1129,137
2,3,18-Jul-14,AmitSahniKiList,N,Comedy,10,4.00,572336,586,54
3,4,4-Jan-13,RajdhaniExpress,N,Drama,7,0.35,42626,86,19
4,5,4-Jul-14,BobbyJasoos,N,Comedy,18,10.80,3113427,4512,1224

In [135]:
df.tail()

,SlNo,ReleaseDate,MovieName,ReleaseTime,Genre,Budget,BoxOfficeCollection,YoutubeViews,YoutubeLikes,YoutubeDislikes
144,145,27-Feb-15,DumLagaKeHaisha,N,Comedy,15,30.00,3250917,8185,615
145,146,13-Mar-15,NH10,N,Thriller,13,32.10,5592977,15464,1513
146,147,20-Mar-15,DilliwaliZaalimGirlfriend,N,Comedy,32,12.00,2316047,4289,807
147,148,20-Mar-15,Hunterrr,N,Comedy,5,11.89,4674795,3706,762
148,149,23-May-14,Kochadaiiyaan,HS,Action,150,120.00,4740727,13466,2649

In [136]:
df.info(149)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SlNo                 149 non-null    int64
 1   ReleaseDate          149 non-null    object
 2   MovieName            149 non-null    object
 3   ReleaseTime          149 non-null    object
 4   Genre                149 non-null    object
 5   Budget               149 non-null    int64
 6   BoxOfficeCollection  149 non-null    float64
 7   YoutubeViews         149 non-null    int64
 8   YoutubeLikes         149 non-null    int64
 9   YoutubeDislikes      149 non-null    int64
dtypes: float64(1), int64(5), object(4)
memory usage: 11.8+ KB

In [137]:
df.describe()

,SlNo,Budget,BoxOfficeCollection,YoutubeViews,YoutubeLikes,YoutubeDislikes
count,149.000000,149.000000,149.000000,1.490000e+02,149.000000,149.000000
mean,75.000000,29.442953,55.667248,3.337920e+06,7877.536913,1207.818792
std,43.156691,28.237981,94.494531,3.504407e+06,12748.047191,1852.692938
min,1.000000,2.000000,0.010000,4.354000e+03,1.000000,1.000000
25%,38.000000,11.000000,8.780000,1.076591e+06,1377.000000,189.000000
50%,75.000000,21.000000,28.000000,2.375050e+06,4111.000000,614.000000
75%,112.000000,35.000000,57.450000,4.550051e+06,9100.000000,1419.000000
max,149.000000,150.000000,735.000000,2.317107e+07,101275.000000,11888.000000

In [138]:
print(df.columns.tolist())

['SlNo', 'ReleaseDate', 'MovieName', 'ReleaseTime', 'Genre', 'Budget', 'BoxOfficeCollection', 'YoutubeViews', 'YoutubeLikes', 'YoutubeDislikes']

In [139]:
print(df.dtypes)

SlNo                     int64
ReleaseDate             object
MovieName               object
ReleaseTime             object
Genre                   object
Budget                   int64
BoxOfficeCollection    float64
YoutubeViews             int64
YoutubeLikes             int64
YoutubeDislikes          int64
dtype: object

In [140]:
display(df["MovieName"].head())

0            2States
1         TableNo.21
2    AmitSahniKiList
3    RajdhaniExpress
4        BobbyJasoos
Name: MovieName, dtype: object

In [141]:
display(df["Genre"].head())

0     Romance
1    Thriller
2      Comedy
3       Drama
4      Comedy
Name: Genre, dtype: object

In [142]:
selected_columns=[
    "MovieName",
    "Genre",
    "Budget",
    "BoxOfficeCollection"
]

display(df[selected_columns].head)

<bound method NDFrame.head of                      MovieName     Genre  Budget  BoxOfficeCollection
0                      2States   Romance      36               104.00
1                   TableNo.21  Thriller      10                12.00
2              AmitSahniKiList    Comedy      10                 4.00
3              RajdhaniExpress     Drama       7                 0.35
4                  BobbyJasoos    Comedy      18                10.80
..                         ...       ...     ...                  ...
144            DumLagaKeHaisha    Comedy      15                30.00
145                       NH10  Thriller      13                32.10
146  DilliwaliZaalimGirlfriend    Comedy      32                12.00
147                   Hunterrr    Comedy       5                11.89
148              Kochadaiiyaan    Action     150               120.00

[149 rows x 4 columns]>

In [143]:
df[selected_columns].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   MovieName            149 non-null    object
 1   Genre                149 non-null    object
 2   Budget               149 non-null    int64
 3   BoxOfficeCollection  149 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 4.8+ KB

In [144]:
display(df[selected_columns].shape)

(149, 4)

In [145]:
#for access row
display(df.iloc[0])
display(df.iloc[0:5])
print("First row, third column: ", df.iloc[0,2])

SlNo                           1
ReleaseDate            18-Apr-14
MovieName                2States
ReleaseTime                   LW
Genre                    Romance
Budget                        36
BoxOfficeCollection        104.0
YoutubeViews             8576361
YoutubeLikes               26622
YoutubeDislikes             2527
Name: 0, dtype: object
   SlNo ReleaseDate        MovieName ReleaseTime     Genre  Budget  \
0     1   18-Apr-14          2States          LW   Romance      36
1     2    4-Jan-13       TableNo.21           N  Thriller      10
2     3   18-Jul-14  AmitSahniKiList           N    Comedy      10
3     4    4-Jan-13  RajdhaniExpress           N     Drama       7
4     5    4-Jul-14      BobbyJasoos           N    Comedy      18

   BoxOfficeCollection  YoutubeViews  YoutubeLikes  YoutubeDislikes
0               104.00       8576361         26622             2527
1                12.00       1087320          1129              137
2                 4.00        572336           586               54
3                 0.35         42626            86               19
4                10.80       3113427          4512             1224
First row, third column:  2States

In [146]:
#level based
print("Movie at index 0: ", df.loc[0, "MovieName"])
display(df.loc[0:4 ,["MovieName", "Genre", "Budget"]])

Movie at index 0:  2States
         MovieName     Genre  Budget
0          2States   Romance      36
1       TableNo.21  Thriller      10
2  AmitSahniKiList    Comedy      10
3  RajdhaniExpress     Drama       7
4      BobbyJasoos    Comedy      18

In [147]:
high_budget = df[df["Budget"]>50]
display(high_budget)

     SlNo ReleaseDate                       MovieName ReleaseTime     Genre  \
14     15    8-Aug-14                   Entertainment           N    Comedy
16     17   25-Jan-13                           Race2          LW  Thriller
26     27   24-Oct-14                    HappyNewYear          LW     Drama
39     40   20-Jun-14                      Humshakals          HS    Comedy
41     42   24-Jan-14                           JaiHo           N    Action
43     44   25-Jul-14                            Kick           N    Action
78     79   15-Aug-14                  SinghamReturns          LW    Action
82     83   31-May-13            YehJawaaniHaiDeewani           N   Romance
89     90   19-Dec-14                              PK          HS     Drama
91     92    5-Dec-14                   ActionJackson           N    Action
92     93    2-Oct-14                        BangBang          FS    Action
96     97    2-Oct-13                        Besharam          LW    Comedy
115   116    9-Aug-13                  ChennaiExpress          FS    Comedy
116   117   15-Aug-13  OnceUponAyTimeInMumbaiDobaara!          FS  Thriller
119   120    1-Nov-13                         Krrish3          FS    Action
130   131    6-Sep-13                         Zanjeer          LW    Action
138   139   23-Jan-15                            Baby           N    Action
148   149   23-May-14                   Kochadaiiyaan          HS    Action

     Budget  BoxOfficeCollection  YoutubeViews  YoutubeLikes  YoutubeDislikes
14       60               163.00       6336058         20472             2843
16       60               162.00       7641333         12617             2138
26      125               383.00       6395202         37585            10269
39       75                63.70       6280868             1                1
41      120               111.00        868743          2783              404
43      100               377.00      18986221        101275            10066
78       90               200.00       8287587         20011             2899
82       70               311.00       5123217         13826             1640
89       85               735.00      13270623         43767             5693
91       90                57.45      13279636         19240             3859
92      140               340.00      15889811         61805             6283
96       85                35.00       5319606         10253             8165
115      75               395.00       1882346          7954             1593
116     100                80.00       3077135          9200             2821
119     115               300.00      23171067         72070            11888
130      75                18.20       2539431          5634              922
138      60               125.00       7968156         29246             2426
148     150               120.00       4740727         13466             2649

In [148]:
print(df["Genre"].unique)

<bound method Series.unique of 0       Romance
1      Thriller
2        Comedy
3         Drama
4        Comedy
         ...
144      Comedy
145    Thriller
146      Comedy
147      Comedy
148      Action
Name: Genre, Length: 149, dtype: object>

In [149]:
filtered = df[
    (df["Budget"]>20)&
    (df["BoxOfficeCollection"]>30)
]

display(filtered.head(20))

    SlNo ReleaseDate               MovieName ReleaseTime     Genre  Budget  \
0      1   18-Apr-14                 2States          LW   Romance      36
7      8   11-Jan-13  MatruKiBijleeKaMandola           N    Comedy      33
12    13   27-Jun-14               EkVillain          HS   Romance      35
14    15    8-Aug-14           Entertainment           N    Comedy      60
16    17   25-Jan-13                   Race2          LW  Thriller      60
22    23   14-Feb-14                  Gunday           N    Action      50
23    24    2-Oct-14                  Haider          FS     Drama      24
25    26    8-Feb-13               Special26           N     Drama      42
26    27   24-Oct-14            HappyNewYear          LW     Drama     125
32    33   23-May-14               Heropanti          HS   Romance      21
33    34   22-Feb-13               KaiPoChe!           N     Drama      30
36    37    6-Jun-14                 Holiday          HS    Action      50
38    39    1-Mar-13       TheAttacksof26/11           N  Thriller      30
39    40   20-Jun-14              Humshakals          HS    Comedy      75
41    42   24-Jan-14                   JaiHo           N    Action     120
43    44   25-Jul-14                    Kick           N    Action     100
45    46   14-Nov-14                 KillDil           N   Romance      35
52    53    4-Apr-14            MainTeraHero          LW    Comedy      40
54    55   29-Mar-13              Himmatwala           N    Action      50
62    63   19-Apr-13             EkThiDaayan          FS  Thriller      24

    BoxOfficeCollection  YoutubeViews  YoutubeLikes  YoutubeDislikes
0                 104.0       8576361         26622             2527
7                  40.0       2435283          4326              647
12                105.5       4518748         13558             1094
14                163.0       6336058         20472             2843
16                162.0       7641333         12617             2138
22                 76.7       3503887          8383             1419
23                 69.0       7048104         23590             2443
25                103.0       1829417          6248              568
26                383.0       6395202         37585            10269
32                 65.0       4005695          8189             1814
33                 62.2       1888754          5686              512
36                129.0       6841635         14182             1997
38                 32.0       1041892          1911              344
39                 63.7       6280868             1                1
41                111.0        868743          2783              404
43                377.0      18986221        101275            10066
45                 36.0       2375050          4358              555
52                 55.0       4903941         12657             2139
54                100.0       2501277             1                1
62                 45.0       1837437          3296              613

In [150]:
filtered_or = df[
    (df["Budget"]>20) |
    (df["YoutubeViews"]>1_000_000)
]

display(filtered_or.head(20))

    SlNo ReleaseDate               MovieName ReleaseTime     Genre  Budget  \
0      1   18-Apr-14                 2States          LW   Romance      36
1      2    4-Jan-13              TableNo.21           N  Thriller      10
4      5    4-Jul-14             BobbyJasoos           N    Comedy      18
5      6   30-May-14              Citylights          HS     Drama       7
6      7   19-Sep-14           Daawat-E-Ishq           N    Comedy      30
7      8   11-Jan-13  MatruKiBijleeKaMandola           N    Comedy      33
8      9   10-Jan-14             DedhIshqiya          LW    Comedy      31
10    11   28-Mar-14             Dishkiyaoon           N    Action      28
11    12   18-Jan-13                  Inkaar           N   Romance       5
12    13   27-Jun-14               EkVillain          HS   Romance      35
14    15    8-Aug-14           Entertainment           N    Comedy      60
16    17   25-Jan-13                   Race2          LW  Thriller      60
18    19   12-Sep-14            FindingFanny           N    Comedy      15
19    20   13-Jun-14                   Fugly          HS    Comedy      10
21    22    7-Mar-14              GulaabGang           N    Action      27
22    23   14-Feb-14                  Gunday           N    Action      50
23    24    2-Oct-14                  Haider          FS     Drama      24
24    25   21-Nov-14             HappyEnding           N   Romance      48
25    26    8-Feb-13               Special26           N     Drama      42
26    27   24-Oct-14            HappyNewYear          LW     Drama     125

    BoxOfficeCollection  YoutubeViews  YoutubeLikes  YoutubeDislikes
0                104.00       8576361         26622             2527
1                 12.00       1087320          1129              137
4                 10.80       3113427          4512             1224
5                 35.00       1076591          1806               84
6                 24.60       3905050          8315             1373
7                 40.00       2435283          4326              647
8                 27.00       2333067          2436              591
10                 6.00       2397647          3308              465
11                10.25       1077723           897              114
12               105.50       4518748         13558             1094
14               163.00       6336058         20472             2843
16               162.00       7641333         12617             2138
18                58.90       6144142         13013             2746
19                12.60       2343109          2963              556
21                14.30       4687259         13219             1605
22                76.70       3503887          8383             1419
23                69.00       7048104         23590             2443
24                21.50       5192338          6928             1120
25               103.00       1829417          6248              568
26               383.00       6395202         37585            10269

In [151]:
filtered_or = df[
    (df["Budget"]>20) |
    (df["YoutubeLikes"]>1_000_000)
]

display(filtered_or.head(20))

    SlNo ReleaseDate               MovieName ReleaseTime     Genre  Budget  \
0      1   18-Apr-14                 2States          LW   Romance      36
6      7   19-Sep-14           Daawat-E-Ishq           N    Comedy      30
7      8   11-Jan-13  MatruKiBijleeKaMandola           N    Comedy      33
8      9   10-Jan-14             DedhIshqiya          LW    Comedy      31
10    11   28-Mar-14             Dishkiyaoon           N    Action      28
12    13   27-Jun-14               EkVillain          HS   Romance      35
14    15    8-Aug-14           Entertainment           N    Comedy      60
16    17   25-Jan-13                   Race2          LW  Thriller      60
21    22    7-Mar-14              GulaabGang           N    Action      27
22    23   14-Feb-14                  Gunday           N    Action      50
23    24    2-Oct-14                  Haider          FS     Drama      24
24    25   21-Nov-14             HappyEnding           N   Romance      48
25    26    8-Feb-13               Special26           N     Drama      42
26    27   24-Oct-14            HappyNewYear          LW     Drama     125
32    33   23-May-14               Heropanti          HS   Romance      21
33    34   22-Feb-13               KaiPoChe!           N     Drama      30
34    35   21-Feb-14                 Highway           N     Drama      30
35    36   22-Feb-13          ZillaGhaziabad           N    Action      36
36    37    6-Jun-14                 Holiday          HS    Action      50
38    39    1-Mar-13       TheAttacksof26/11           N  Thriller      30

    BoxOfficeCollection  YoutubeViews  YoutubeLikes  YoutubeDislikes
0                104.00       8576361         26622             2527
6                 24.60       3905050          8315             1373
7                 40.00       2435283          4326              647
8                 27.00       2333067          2436              591
10                 6.00       2397647          3308              465
12               105.50       4518748         13558             1094
14               163.00       6336058         20472             2843
16               162.00       7641333         12617             2138
21                14.30       4687259         13219             1605
22                76.70       3503887          8383             1419
23                69.00       7048104         23590             2443
24                21.50       5192338          6928             1120
25               103.00       1829417          6248              568
26               383.00       6395202         37585            10269
32                65.00       4005695          8189             1814
33                62.20       1888754          5686              512
34                27.25       3043012          9100              971
35                16.00       1551786          1753              619
36               129.00       6841635         14182             1997
38                32.00       1041892          1911              344

In [152]:
genres_to_find = df["Genre"].dropna().unique()[:3]
print("Genres selected",genres_to_find )
display(df.loc[df["Genre"].isin(genres_to_find)].head(20))

Genres selected ['Romance' 'Thriller' 'Comedy']
    SlNo ReleaseDate               MovieName ReleaseTime     Genre  Budget  \
0      1   18-Apr-14                 2States          LW   Romance      36
1      2    4-Jan-13              TableNo.21           N  Thriller      10
2      3   18-Jul-14         AmitSahniKiList           N    Comedy      10
4      5    4-Jul-14             BobbyJasoos           N    Comedy      18
6      7   19-Sep-14           Daawat-E-Ishq           N    Comedy      30
7      8   11-Jan-13  MatruKiBijleeKaMandola           N    Comedy      33
8      9   10-Jan-14             DedhIshqiya          LW    Comedy      31
11    12   18-Jan-13                  Inkaar           N   Romance       5
12    13   27-Jun-14               EkVillain          HS   Romance      35
14    15    8-Aug-14           Entertainment           N    Comedy      60
16    17   25-Jan-13                   Race2          LW  Thriller      60
17    18    6-Jun-14              Filmistaan          HS    Comedy      10
18    19   12-Sep-14            FindingFanny           N    Comedy      15
19    20   13-Jun-14                   Fugly          HS    Comedy      10
20    21    1-Feb-13                   David           N  Thriller      10
24    25   21-Nov-14             HappyEnding           N   Romance      48
28    29   18-Jul-14              HateStory2           N  Thriller      12
30    31    7-Feb-14               Heartless           N  Thriller      12
31    32   15-Feb-13                 Murder3          FS  Thriller      12
32    33   23-May-14               Heropanti          HS   Romance      21

    BoxOfficeCollection  YoutubeViews  YoutubeLikes  YoutubeDislikes
0                104.00       8576361         26622             2527
1                 12.00       1087320          1129              137
2                  4.00        572336           586               54
4                 10.80       3113427          4512             1224
6                 24.60       3905050          8315             1373
7                 40.00       2435283          4326              647
8                 27.00       2333067          2436              591
11                10.25       1077723           897              114
12               105.50       4518748         13558             1094
14               163.00       6336058         20472             2843
16               162.00       7641333         12617             2138
17                 6.00        989096          1608              173
18                58.90       6144142         13013             2746
19                12.60       2343109          2963              556
20                 3.65        839270          1542               95
24                21.50       5192338          6928             1120
28                27.16      13798789         15708             5226
30                 1.50       4823892          5797              227
31                25.00       2249055          1879              747
32                65.00       4005695          8189             1814

In [153]:
ReleaseDate_to_find = df["ReleaseDate"].dropna().unique()[:3]
print("ReleaseDate selected",ReleaseDate_to_find )
display(df.loc[df["ReleaseDate"].isin(ReleaseDate_to_find)].head(20))

ReleaseDate selected ['18-Apr-14' '4-Jan-13' '18-Jul-14']
    SlNo ReleaseDate        MovieName ReleaseTime     Genre  Budget  \
0      1   18-Apr-14          2States          LW   Romance      36
1      2    4-Jan-13       TableNo.21           N  Thriller      10
2      3   18-Jul-14  AmitSahniKiList           N    Comedy      10
3      4    4-Jan-13  RajdhaniExpress           N     Drama       7
28    29   18-Jul-14       HateStory2           N  Thriller      12
98    99   18-Jul-14          Pizza3D           N  Thriller      10

    BoxOfficeCollection  YoutubeViews  YoutubeLikes  YoutubeDislikes
0                104.00       8576361         26622             2527
1                 12.00       1087320          1129              137
2                  4.00        572336           586               54
3                  0.35         42626            86               19
28                27.16      13798789         15708             5226
98                 4.35        838943          1116              153

In [154]:
df

,SlNo,ReleaseDate,MovieName,ReleaseTime,Genre,Budget,BoxOfficeCollection,YoutubeViews,YoutubeLikes,YoutubeDislikes
0,1,18-Apr-14,2States,LW,Romance,36,104.00,8576361,26622,2527
1,2,4-Jan-13,TableNo.21,N,Thriller,10,12.00,1087320,1129,137
2,3,18-Jul-14,AmitSahniKiList,N,Comedy,10,4.00,572336,586,54
3,4,4-Jan-13,RajdhaniExpress,N,Drama,7,0.35,42626,86,19
4,5,4-Jul-14,BobbyJasoos,N,Comedy,18,10.80,3113427,4512,1224
...,...,...,...,...,...,...,...,...,...,...
144,145,27-Feb-15,DumLagaKeHaisha,N,Comedy,15,30.00,3250917,8185,615
145,146,13-Mar-15,NH10,N,Thriller,13,32.10,5592977,15464,1513
146,147,20-Mar-15,DilliwaliZaalimGirlfriend,N,Comedy,32,12.00,2316047,4289,807
147,148,20-Mar-15,Hunterrr,N,Comedy,5,11.89,4674795,3706,762
148,149,23-May-14,Kochadaiiyaan,HS,Action,150,120.00,4740727,13466,2649

In [155]:
print("Average budget: ", df["Budget"].mean())
print("max budget: ", df["Budget"].max())
print("min budget: ", df["Budget"].min())

print("Average BoxOfficeCollection: ", df["BoxOfficeCollection"].max())
print("min BoxOfficeCollection: ", df["BoxOfficeCollection"].min())

Average budget:  29.44295302013423
max budget:  150
min budget:  2
Average BoxOfficeCollection:  735.0
min BoxOfficeCollection:  0.01

In [156]:
print("Average YoutubeViews : ", df["YoutubeViews"].mean())
print(" max YoutubeViews : ", df["YoutubeViews"].max())

Average YoutubeViews :  3337919.912751678
 max YoutubeViews :  23171067

In [157]:
max_Budget=df["Budget"].max()

print("Max Budget: ", max_Budget)
print(df[df["Budget"]==max_Budget])

Max Budget:  150
     SlNo ReleaseDate      MovieName ReleaseTime   Genre  Budget  \
148   149   23-May-14  Kochadaiiyaan          HS  Action     150

     BoxOfficeCollection  YoutubeViews  YoutubeLikes  YoutubeDislikes
148                120.0       4740727         13466             2649

In [158]:
min_YoutubeViews=df["YoutubeViews"].min()

print("min YoutubeViews: ", min_YoutubeViews)

min YoutubeViews:  4354

In [159]:
max_BoxOfficeCollection=df["BoxOfficeCollection"].max()

print("max BoxOfficeCollection: ", max_BoxOfficeCollection)
print(df[df["BoxOfficeCollection"]==max_BoxOfficeCollection])

max BoxOfficeCollection:  735.0
    SlNo ReleaseDate MovieName ReleaseTime  Genre  Budget  \
89    90   19-Dec-14        PK          HS  Drama      85

    BoxOfficeCollection  YoutubeViews  YoutubeLikes  YoutubeDislikes
89                735.0      13270623         43767             5693

In [160]:
display(df.sort_values("Budget").head(10))

     SlNo ReleaseDate     MovieName ReleaseTime     Genre  Budget  \
9      10   11-Jan-13     Gangoobai           N     Drama       2
60     61    9-May-14       Mastram          HS    Comedy       2
104   105   12-Jul-13      B.A.Pass           N     Drama       2
55     56    9-May-14     Manjunath          HS     Drama       3
15     16   18-Jan-13       Bandook           N    Action       4
126   127   11-Oct-13   BaatBanGayi          FS    Comedy       4
113   114   26-Jul-13         Nasha           N  Thriller       4
13     14   18-Jan-13  MumbaiMirror           N    Action       4
63     64   17-Jan-14    MissLovely           N     Drama       5
81     82   28-Nov-14         Ungli           N     Drama       5

     BoxOfficeCollection  YoutubeViews  YoutubeLikes  YoutubeDislikes
9                   0.01          4354             1                1
60                  3.00       3557585          3927             1364
104                 5.90       2240961           842              348
55                  1.75        370106           991               35
15                  0.09         28391             8               14
126                 1.50         23186             9                4
113                 8.00        613448           288              188
13                  1.80        235767           192              164
63                  0.70        808439           328               95
81                 13.80       2763615          6907              489

In [161]:

display(df.sort_values("Budget", ascending=False).head(5))

     SlNo ReleaseDate      MovieName ReleaseTime   Genre  Budget  \
148   149   23-May-14  Kochadaiiyaan          HS  Action     150
92     93    2-Oct-14       BangBang          FS  Action     140
26     27   24-Oct-14   HappyNewYear          LW   Drama     125
41     42   24-Jan-14          JaiHo           N  Action     120
119   120    1-Nov-13        Krrish3          FS  Action     115

     BoxOfficeCollection  YoutubeViews  YoutubeLikes  YoutubeDislikes
148                120.0       4740727         13466             2649
92                 340.0      15889811         61805             6283
26                 383.0       6395202         37585            10269
41                 111.0        868743          2783              404
119                300.0      23171067         72070            11888

In [162]:
display(
    df.sort_values(["Genre","Budget"],ascending=[True,False]).head(10))

     SlNo ReleaseDate       MovieName ReleaseTime   Genre  Budget  \
148   149   23-May-14   Kochadaiiyaan          HS  Action     150
92     93    2-Oct-14        BangBang          FS  Action     140
41     42   24-Jan-14           JaiHo           N  Action     120
119   120    1-Nov-13         Krrish3          FS  Action     115
43     44   25-Jul-14            Kick           N  Action     100
78     79   15-Aug-14  SinghamReturns          LW  Action      90
91     92    5-Dec-14   ActionJackson           N  Action      90
130   131    6-Sep-13         Zanjeer          LW  Action      75
138   139   23-Jan-15            Baby           N  Action      60
22     23   14-Feb-14          Gunday           N  Action      50

     BoxOfficeCollection  YoutubeViews  YoutubeLikes  YoutubeDislikes
148               120.00       4740727         13466             2649
92                340.00      15889811         61805             6283
41                111.00        868743          2783              404
119               300.00      23171067         72070            11888
43                377.00      18986221        101275            10066
78                200.00       8287587         20011             2899
91                 57.45      13279636         19240             3859
130                18.20       2539431          5634              922
138               125.00       7968156         29246             2426
22                 76.70       3503887          8383             1419

In [163]:
df["Profit"]=df["BoxOfficeCollection"] - df["Budget"]
display(df[["MovieName","Budget","BoxOfficeCollection","Profit"]].head(148))

                     MovieName  Budget  BoxOfficeCollection  Profit
0                      2States      36               104.00   68.00
1                   TableNo.21      10                12.00    2.00
2              AmitSahniKiList      10                 4.00   -6.00
3              RajdhaniExpress       7                 0.35   -6.65
4                  BobbyJasoos      18                10.80   -7.20
..                         ...     ...                  ...     ...
143                   Badlapur      23                77.00   54.00
144            DumLagaKeHaisha      15                30.00   15.00
145                       NH10      13                32.10   19.10
146  DilliwaliZaalimGirlfriend      32                12.00  -20.00
147                   Hunterrr       5                11.89    6.89

[148 rows x 4 columns]

In [164]:
df["Result"]=np.where(
    df["BoxOfficeCollection"] > df["Budget"],
    "hit",
    "flop"
)
display(df[["MovieName","Budget","BoxOfficeCollection","Result"]].head(10))

                MovieName  Budget  BoxOfficeCollection Result
0                 2States      36               104.00    hit
1              TableNo.21      10                12.00    hit
2         AmitSahniKiList      10                 4.00   flop
3         RajdhaniExpress       7                 0.35   flop
4             BobbyJasoos      18                10.80   flop
5              Citylights       7                35.00    hit
6           Daawat-E-Ishq      30                24.60   flop
7  MatruKiBijleeKaMandola      33                40.00    hit
8             DedhIshqiya      31                27.00   flop
9               Gangoobai       2                 0.01   flop

In [165]:
print(df["Result"].value_counts())

Result
hit     83
flop    66
Name: count, dtype: int64

In [166]:
most_common_genre=df["Genre"].value_counts().idxmax()
print("Most common genre: ", most_common_genre)

Most common genre:  Comedy

In [167]:
avg_budget_by_genre=(
    df.groupby("Genre")["Budget"]
    .mean()
    .sort_values(ascending=False)
)

display(avg_budget_by_genre)

Genre
Action      56.958333
Comedy      25.277778
Romance     25.160000
Drama       24.200000
Thriller    21.862069
Name: Budget, dtype: float64

In [168]:
avg_collection_by_genre=(
    df.groupby("Genre")["BoxOfficeCollection"]
    .mean()
    .sort_values(ascending=False)
)

display(avg_collection_by_genre)

Genre
Action      91.680833
Drama       65.793143
Romance     52.841200
Comedy      46.115000
Thriller    27.936207
Name: BoxOfficeCollection, dtype: float64

In [169]:
avg_likes_by_genre=(
    df.groupby("Genre")["YoutubeLikes"]
    .mean()
    .sort_values(ascending=False)
)

display(avg_likes_by_genre)

Genre
Action      16744.708333
Drama        7973.628571
Romance      7089.640000
Thriller     4941.793103
Comedy       4784.722222
Name: YoutubeLikes, dtype: float64

In [170]:
# agg = aggregate
genre_summary=(
   df.groupby("Genre")["YoutubeLikes"]
   .agg(["mean", "max", "count" , "min" , "median"])
    .sort_values("mean", ascending=False)
)

display(genre_summary)

                  mean     max  count  min  median
Genre
Action    16744.708333  101275     24    1  7951.0
Drama      7973.628571   43767     35    1  3656.0
Romance    7089.640000   26622     25    1  4853.0
Thriller   4941.793103   18907     29   61  2974.0
Comedy     4784.722222   20472     36    1  3365.0

In [171]:
YoutubeLikes_summary=(
    df["YoutubeLikes"]
      .agg(["max", "count", "min", "median"])
      .sort_values(ascending=False)
)
display(YoutubeLikes_summary)

max       101275.0
median      4111.0
count        149.0
min            1.0
Name: YoutubeLikes, dtype: float64

In [172]:
display(df["ReleaseTime"].value_counts())

ReleaseTime
N     99
HS    18
FS    17
LW    15
Name: count, dtype: int64

In [173]:
display(df["ReleaseDate"].value_counts())

ReleaseDate
9-May-14     5
18-Jul-14    3
28-Mar-14    3
7-Mar-14     3
18-Jan-13    3
            ..
23-Jan-15    1
13-Feb-15    1
20-Feb-15    1
27-Feb-15    1
13-Mar-15    1
Name: count, Length: 102, dtype: int64

In [174]:
release_genre_count=(
    df.groupby(["Genre", "ReleaseTime"])
    .size()
    .sort_values(ascending=False)
)

display(release_genre_count)

Genre     ReleaseTime
Drama     N              24
Comedy    N              23
Thriller  N              22
Action    N              15
Romance   N              15
Drama     HS              6
Comedy    LW              5
          HS              5
Thriller  FS              4
Romance   LW              4
Drama     FS              4
Action    FS              3
          LW              3
          HS              3
Romance   FS              3
Comedy    FS              3
Romance   HS              3
Thriller  LW              2
Drama     LW              1
Thriller  HS              1
dtype: int64

In [175]:
#str= removing leadind and whitespace
df["Genre"]= df["Genre"].astype("string").str.strip()
print(df["Genre"].unique())

<StringArray>
['Romance', 'Thriller', 'Comedy', 'Drama', 'Action']
Length: 5, dtype: string

In [176]:
df["Genre"]= df["Genre"].str.upper()
print(df["Genre"].value_counts())

Genre
COMEDY      36
DRAMA       35
THRILLER    29
ROMANCE     25
ACTION      24
Name: count, dtype: Int64

In [177]:
missing_values=df.isnull().sum()

display(missing_values)

SlNo                   0
ReleaseDate            0
MovieName              0
ReleaseTime            0
Genre                  0
Budget                 0
BoxOfficeCollection    0
YoutubeViews           0
YoutubeLikes           0
YoutubeDislikes        0
Profit                 0
Result                 0
dtype: int64

In [184]:
df_clean=df.drop_duplicates().copy()

print("Before: ", len(df))
print("After: ", len(df_clean))

Before:  149
After:  149

In [192]:
import pandas as pd

print(type(pd.to_datetime))

<class 'pandas.core.series.Series'>

In [195]:
import pandas as pd
import importlib

pd = importlib.reload(pd)

df_clean["ReleaseDate"] = pd.to_datetime(
    df_clean["ReleaseDate"],
    errors="coerce"
)

print(df_clean["ReleaseDate"].dtype)

display(df_clean[["ReleaseDate", "MovieName"]].head())

datetime64[ns]
  ReleaseDate        MovieName
0  2014-04-18          2States
1  2013-01-04       TableNo.21
2  2014-07-18  AmitSahniKiList
3  2013-01-04  RajdhaniExpress
4  2014-07-04      BobbyJasoos

/tmp/ipykernel_3830/1489634727.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_clean["ReleaseDate"] = pd.to_datetime(

In [180]:
avg_budget_by_genre=(
    df.groupby("Genre")["Budget"]
    .mean()
    .sort_values(ascending=False)
)

display(avg_budget_by_genre)

Genre
ACTION      56.958333
COMEDY      25.277778
ROMANCE     25.160000
DRAMA       24.200000
THRILLER    21.862069
Name: Budget, dtype: float64